---
- name: Gather Host Information
  hosts: all
  gather_facts: yes

  tasks:
  - name: Print VM details
    debug:
      msg:
        - "Hostname: {{ ansible_facts['hostname'] }}"
        - "OS Name: {{ ansible_facts['distribution'] }}"
        - "OS Version: {{ ansible_facts['distribution_version'] }}"
        - "IPaddr: {{ ansible_facts['default_ipv4']['address'] }}"